---
docker_auth: &docker_auth
  username: $DOCKERHUB_USERNAME
  password: $DOCKERHUB_PASSWORD

defaults: &defaults
  docker:
    - image: greenpeaceinternational/circleci-base:latest
      auth:
        <<: *docker_auth

version: 2

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - run: make lint | tee /tmp/lint.log
      - run:
          name: Notify failure
          when: on_fail
          command: |
            TYPE="Test" \
            EXTRA_TEXT="\`\`\`$(cat /tmp/lint.log)\`\`\`" \
            notify-job-failure.sh
  deploy:
    <<: *defaults
    environment:
      GOOGLE_PROJECT_ID: planet-4-151612
    steps:
      - checkout
      - run:
          name: Setup Google Cloud SDK
          command: |
              activate-gcloud-account.sh
      - deploy:
          name: Deploy to development cluster
          command: make deploy | tee /tmp/deploy.log
      - run:
          name: Notify failure
          when: on_fail
          command: |
            TYPE="Deploy" \
            EXTRA_TEXT="\`\`\`
            $(cat /tmp/deploy.log)
            \`\`\`" \
            notify-job-failure.sh
      - run: |
          TYPE="Deploy" \
          EXTRA_TEXT="\`\`\`$(make history)\`\`\`" \
          notify-job-success.sh

workflows:
  version: 2
  commit:
    jobs:
      - lint:
          context: org-global
      - deploy:
          context: org-global
          requires:
            - lint
          filters:
            branches:
              only:
                - develop
